version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cicd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cicd_db
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - cicd-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cicd-api
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: cicd_db
      DB_USER: apiuser
      DB_PASSWORD: apipassword
      LOGTAIL_SOURCE_TOKEN: ${LOGTAIL_SOURCE_TOKEN:-fake-token-for-dev}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - mysql
    networks:
      - cicd-network
    restart: unless-stopped
    command: npm run dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cicd-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - cicd-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  cicd-network:
    driver: bridge 